/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as odz1155Sol from "./Odz1155.sol";
export type { odz1155Sol };
export type { ISPHook } from "./ISPHook";
export type { Lock } from "./Lock";
export type { Odz20 } from "./Odz20";
