/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IOdz20,
  IOdz20Interface,
} from "../../../contracts/Odz1155.sol/IOdz20";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IOdz20__factory {
  static readonly abi = _abi;
  static createInterface(): IOdz20Interface {
    return new Interface(_abi) as IOdz20Interface;
  }
  static connect(address: string, runner?: ContractRunner | null): IOdz20 {
    return new Contract(address, _abi, runner) as unknown as IOdz20;
  }
}
